name: setup
description: Install Rust, pnpm, and node

runs:
  using: composite
  steps:
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy

    - uses: Swatinem/rust-cache@v2

    # Crossflow frontend runs install
    - uses: pnpm/setup@v2
      with:
        version: 11
        runtime: node@22
        install: false
